name: Job dependencies practice
on:
 push:
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Build application
    run: echo "Building application"
  test:
    needs: build
    runs-on: ubuntu-latest
  steps: 
   - name: Run tests
     run: echo "Running application"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: Deploy application
      run: echo: "Deploying application"

 
 
