name: Job dependencies practice
on:
 push:
 workflow_dispatch:
env:
 APP_NAME: my application
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Use secret
     run: echo"MYsecret is $
 {{secrets.MY_secret}}"
    - name: build application
      run: echo"building$APP_NAME..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - name: run tests
      continue-on-error: true
      run: exit 1
    - name: handle test fail
      if: failure
      run: the test step fail
  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run security scan
      run: echo "Running security scaning..."
  deploy: 
    needs: [test,security]
    runs-on: ubuntu-latest
    steps:
    - name: deploy application
      run: echo "Deploying application..."
  notify:
   needs: deploy
   if: success()
   runs-on: ubuntu-latest
   steps: 
   - name: success message
     run: echo "deploying completed successfully!"
  failure- handler:
   needs: deploy
   if: faillure
   runs-on: ubuntu-latest
   steps:
   - name: failure message
     run: echo " something went wrong!"
  
 
   
     
